// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_yzyJxWF1v6XYfMpJdyIh8Ldj9mFpVpA',
    appId: '1:750374077754:web:92fc455a36ade046b5fc03',
    messagingSenderId: '750374077754',
    projectId: 'kurutomodev',
    authDomain: 'kurutomodev.firebaseapp.com',
    storageBucket: 'kurutomodev.appspot.com',
    measurementId: 'G-DCL0NLKYH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0krggQeFuKa79PDmszvSORyWHFohD24',
    appId: '1:750374077754:android:961b0e773e1a0872b5fc03',
    messagingSenderId: '750374077754',
    projectId: 'kurutomodev',
    storageBucket: 'kurutomodev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3jap0tgcMp9Aos9561gTSd-WrmX5vAl4',
    appId: '1:750374077754:ios:0ee84f0825702fb7b5fc03',
    messagingSenderId: '750374077754',
    projectId: 'kurutomodev',
    storageBucket: 'kurutomodev.appspot.com',
    iosClientId: '750374077754-9ug4ea338r72090joq1u7tnhsk41cqbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurutomoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3jap0tgcMp9Aos9561gTSd-WrmX5vAl4',
    appId: '1:750374077754:ios:0ee84f0825702fb7b5fc03',
    messagingSenderId: '750374077754',
    projectId: 'kurutomodev',
    storageBucket: 'kurutomodev.appspot.com',
    iosClientId: '750374077754-9ug4ea338r72090joq1u7tnhsk41cqbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurutomoApp',
  );
}
